FROM openjdk:8u181-jdk

RUN apk update && \
    apk upgrade && \
    apk --no-cache add curl nodejs maven
    
RUN curl -ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xz -C /
